//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ControladorPersonaje.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControladorPersonaje: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControladorPersonaje()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControladorPersonaje"",
    ""maps"": [
        {
            ""name"": ""ControlCamara"",
            ""id"": ""5dd02e92-6542-4c17-8019-9070a86bde8d"",
            ""actions"": [
                {
                    ""name"": ""ZoomMouse"",
                    ""type"": ""Value"",
                    ""id"": ""33878be4-92af-4094-a778-f526164163e7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GamepadZoom"",
                    ""type"": ""Value"",
                    ""id"": ""31c1fc95-fff7-4140-a43c-24f00db5be4f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2bbae983-726c-4432-8485-bc9d23190b45"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""564e62e9-4571-42bc-9078-a10ea8fc9060"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5f3abd6b-2f86-4f17-90ed-31e67e918bef"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8f8c7b92-312b-4139-ac4f-ab4e4aadb692"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""fc9ee3a2-01e5-4db6-8771-ce29ab5683eb"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""aeb7f7d2-4a77-4952-bafc-90fcb9e99c37"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""83b8f8ec-3821-4c35-b951-3b55c5c9a43e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0dc85819-34ce-4a40-a1a2-dfe15b034409"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""e58061fa-8097-41a7-b38e-8bee36acc7a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d12710c5-8aff-4523-ab45-e26b962efc27"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""151c31fa-cccf-40ed-a39e-f62db66ff323"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c98263b9-ca6e-4aef-8bf0-cdb237958b45"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""994f10c3-d85e-4d07-bc60-4e3b08d8f2fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""168a7a48-5f81-46a7-a66c-228ca658a12e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5125416-5e96-45e6-a1c8-cdc5339de701"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlCamara
        m_ControlCamara = asset.FindActionMap("ControlCamara", throwIfNotFound: true);
        m_ControlCamara_ZoomMouse = m_ControlCamara.FindAction("ZoomMouse", throwIfNotFound: true);
        m_ControlCamara_GamepadZoom = m_ControlCamara.FindAction("GamepadZoom", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Movimiento = m_Gameplay.FindAction("Movimiento", throwIfNotFound: true);
        m_Gameplay_Saltar = m_Gameplay.FindAction("Saltar", throwIfNotFound: true);
    }

    ~@ControladorPersonaje()
    {
        UnityEngine.Debug.Assert(!m_ControlCamara.enabled, "This will cause a leak and performance issues, ControladorPersonaje.ControlCamara.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Gameplay.enabled, "This will cause a leak and performance issues, ControladorPersonaje.Gameplay.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlCamara
    private readonly InputActionMap m_ControlCamara;
    private List<IControlCamaraActions> m_ControlCamaraActionsCallbackInterfaces = new List<IControlCamaraActions>();
    private readonly InputAction m_ControlCamara_ZoomMouse;
    private readonly InputAction m_ControlCamara_GamepadZoom;
    public struct ControlCamaraActions
    {
        private @ControladorPersonaje m_Wrapper;
        public ControlCamaraActions(@ControladorPersonaje wrapper) { m_Wrapper = wrapper; }
        public InputAction @ZoomMouse => m_Wrapper.m_ControlCamara_ZoomMouse;
        public InputAction @GamepadZoom => m_Wrapper.m_ControlCamara_GamepadZoom;
        public InputActionMap Get() { return m_Wrapper.m_ControlCamara; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlCamaraActions set) { return set.Get(); }
        public void AddCallbacks(IControlCamaraActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlCamaraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlCamaraActionsCallbackInterfaces.Add(instance);
            @ZoomMouse.started += instance.OnZoomMouse;
            @ZoomMouse.performed += instance.OnZoomMouse;
            @ZoomMouse.canceled += instance.OnZoomMouse;
            @GamepadZoom.started += instance.OnGamepadZoom;
            @GamepadZoom.performed += instance.OnGamepadZoom;
            @GamepadZoom.canceled += instance.OnGamepadZoom;
        }

        private void UnregisterCallbacks(IControlCamaraActions instance)
        {
            @ZoomMouse.started -= instance.OnZoomMouse;
            @ZoomMouse.performed -= instance.OnZoomMouse;
            @ZoomMouse.canceled -= instance.OnZoomMouse;
            @GamepadZoom.started -= instance.OnGamepadZoom;
            @GamepadZoom.performed -= instance.OnGamepadZoom;
            @GamepadZoom.canceled -= instance.OnGamepadZoom;
        }

        public void RemoveCallbacks(IControlCamaraActions instance)
        {
            if (m_Wrapper.m_ControlCamaraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlCamaraActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlCamaraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlCamaraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlCamaraActions @ControlCamara => new ControlCamaraActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Movimiento;
    private readonly InputAction m_Gameplay_Saltar;
    public struct GameplayActions
    {
        private @ControladorPersonaje m_Wrapper;
        public GameplayActions(@ControladorPersonaje wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_Gameplay_Movimiento;
        public InputAction @Saltar => m_Wrapper.m_Gameplay_Saltar;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Movimiento.started += instance.OnMovimiento;
            @Movimiento.performed += instance.OnMovimiento;
            @Movimiento.canceled += instance.OnMovimiento;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Movimiento.started -= instance.OnMovimiento;
            @Movimiento.performed -= instance.OnMovimiento;
            @Movimiento.canceled -= instance.OnMovimiento;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IControlCamaraActions
    {
        void OnZoomMouse(InputAction.CallbackContext context);
        void OnGamepadZoom(InputAction.CallbackContext context);
    }
    public interface IGameplayActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
    }
}
